version: '3'
services:
    ubuntu:
        ports:
            - 80:80
        build: .
        volumes:
            - ../:/var/www/html:z
        links:
            - 'mariadb'

    mariadb:
        image: mariadb:10.3
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "America/Caracas"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'rolivares'
            MYSQL_PASSWORD: 'rolivares123'
            MYSQL_DATABASE: 'test'

volumes:
    mariadb:
